### ISSUE TITLE
Slide Vertical Alignment

### ISSUE THREAD

**Issue by JoeBSong** [ideinteractive/simple-logo-carousel#8]
When making the Slide Vertical Alignment set to Bottom, upon updating it is set to Top

Before
![Capture](https://user-images.githubusercontent.com/31709530/89742569-9df4c080-da60-11ea-9549-e3f90bd51f66.PNG)

After
![Capture2](https://user-images.githubusercontent.com/31709530/89742574-a5b46500-da60-11ea-97c4-1abf07b08328.PNG)

**Comment by tvledesign** [comment]
Fixed up a typo in the script outputting the values. Should be fixed now. Please confirm @JoeBSong .

**Comment by JoeBSong** [comment]
Confirmed fixed
